routes/auth.py
from flask import Blueprint, redirect, url_for, render_template, request, flash, current_app
from flask_login import login_required, logout_user, UserMixin, current_user

from utils.log import logger, datos_log
from Services.authenticator import Autenticate
from models.Userdb import Usuarios
from utils.db import db

authentication = Blueprint("authentication", __name__)


@authentication.route("/")
def root():
    datos_request = datos_log(request)
    logger.info(datos_request)
    if current_user.is_authenticated:
        return redirect(url_for("dashboard.dashboard_page"))
    else:
        return redirect(url_for("authentication.login"))


@authentication.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        datos_request = datos_log(request)
        logger.info(datos_request)
        username = request.form["username"]
        password = request.form["password"]

        userdata = db.query(Usuarios).filter_by(username=username).first()

        if userdata != None:
            if Autenticate.login(userdata, password):
                if userdata.deleted == True:
                    logger.error("User id " + str(current_user.id) + " | " + current_user.nombres + " | " + current_user.apellidos + " login fallido, usuario inhabilitado")
                    flash({"title": "Chronos SNI", "message": "Usuario inhabilitado"}, "error")
                    logout_user()
                    return redirect(url_for("authentication.login"))
                else:
                    logger.info("User id " + str(current_user.id) + " | " + current_user.nombres + " | " + current_user.apellidos + " login exitoso")
                    mensaje = f"Bienvenido " + current_user.nombres + " " + current_user.apellidos
                    flash({"title": "Chronos SNI", "message": mensaje}, "success")
                    return redirect(url_for("dashboard.dashboard_page"))
            else:
                # no puedes colocar attributos del usuarios si no esta authenticate
                logger.warning("User id " + username + " | error clave")
                flash({"title": "Chronos SNI", "message": "Error clave"}, "error")
                return redirect(url_for("authentication.login"))
        else:
            flash({"title": "Chronos SNI", "message": "Usuario " + username + " no registrado"}, "error")
            logger.error("Usuario " + username + "no registrado error login")
            return render_template("auth/login.html")

    else:

        datos_request = datos_log(request)
        logger.info(datos_request)
    return render_template("auth/login.html")


@authentication.route("/logout")
def logout():
    if current_user.is_authenticated:
        logger.info("User id " + str(current_user.id) + " | " + current_user.username + " | finalizo sesión")
        flash({"title": "Chronos SNI", "message": "Usuario " + current_user.username + " finaliza sesión"}, "info")
        logout_user()
        return redirect(url_for("authentication.root"))
    else:

        flash({"title": "Chronos SNI", "message": "Ningún usuario ha iniciado sesión"}, "info")

    return redirect(url_for("authentication.root"))

routes/usuarios.py
from flask import Blueprint, request, redirect, url_for, render_template, flash, jsonify
from flask_login import login_required, current_user
from models.Userdb import Usuarios
from utils.db import db
from utils.log import logger, datos_log
from werkzeug.security import generate_password_hash
from datetime import datetime


usuarios = Blueprint("usuarios", __name__)


# validacion si el usario tiene privilegios para el modulo de usuarios #tambien evita que ingrese a las endpoint manualmente
def isadmin(user):
    if user.rol != "admin":
        flash({"title": "Chronos SNI", "message": "Un administrador solo puede gestionar usuarios"}, "error")
        logger.error("User id " + str(user.id) + " | " + user.username + " | intenta acceder al modulo usuarios")
        return False
    else:
        return True


@usuarios.route("/usuarios")
@login_required
def send_usuarios():
    datos_request = datos_log(request)
    logger.info(datos_request)

    if isadmin(current_user):
        print("rico")
        registros = db.query(Usuarios).all()
        logger.info("User id " + str(current_user.id) + " | " + current_user.username + " | consulta usuarios")
        return render_template("mod_usuarios/usuarios.html", usuarios=registros, deleted=False)
    else:
        return redirect(url_for("dashboard.dashboard_page"))


@usuarios.route("/usuarios_deleted")
@login_required
def send_deleted_usuarios():
    datos_request = datos_log(request)
    logger.info(datos_request)
    if isadmin(current_user):
        registros = db.query(Usuarios).filter_by(deleted=True).all()
        logger.info("User id " + str(current_user.id) + " | " + current_user.username + " | consulta usuarios deleted")
        return render_template("mod_usuarios/usuarios.html", usuarios=registros, deleted=True)
    else:
        return redirect(url_for("dashboard.dashboard_page"))


@usuarios.route("/registraru", methods=["GET", "POST"])
@login_required
def registro_usuarios():
    datos_request = datos_log(request)
    logger.info(datos_request)
    if request.method == "GET":
        if isadmin(current_user):
            logger.info("User id " + str(current_user.id) + " | " + current_user.username + " | ingresa al registro de usuario")
            return render_template("mod_usuarios/registrou.html")
        else:
            return redirect(url_for("dashboard.dashboard_page"))

    else:

        # Nota: la clave y confirmacion ahora se estan validando en el front con un script antes del submit
        # la validacion del username no este en uso esta validad antes del submit con una consulta al endpoint check_username
        # validando que las claves suministradas coincidan
        fecha = datetime.now()
        fechar = fecham = fecha.strftime("%Y/%m/%d %H:%M:%S")
        new_user = Usuarios(
            request.form["username"],
            generate_password_hash(request.form["clave"]),
            request.form["nombres"],
            request.form["apellidos"],
            request.form["ci"],
            request.form["rol"],
            fechar,
            fecham,
            False,
        )
        db.add(new_user)
        db.commit()
        logger.info("User id " + str(current_user.id) + " | " + current_user.username + " | Registra el usuario: " + new_user.username)
        mensaje = f"Usuario: " + new_user.username + " registrado satisfactoriamente"
        flash({"title": "Chronos SNI", "message": mensaje}, "success")
        return redirect(url_for("usuarios.send_usuarios"))


@usuarios.route("/check-username")
@login_required
def check_username():
    username = request.args.get("username")
    exists = db.query(Usuarios).filter_by(username=username).first() is not None
    return jsonify({"exists": exists})


@usuarios.route("/check-username-mod")
@login_required
def check_username_mod():
    username = request.args.get("username")
    id = request.args.get("id")
    exists = db.query(Usuarios).filter(Usuarios.username == username, Usuarios.id != id).first() is not None
    return jsonify({"exists": exists})


def validacion_usuario_soporte(id, current_user_id):
    # El id 2 solo pueda ser modificado por el mismo
    if id == "2" and current_user_id == 2:
        return True
    elif id == "2" and current_user_id != 2:
        return False
    else:
        return True


@usuarios.route("/modificar_user/<id>", methods=["GET", "POST"])
@login_required
def modificar_user(id):
    datos_request = datos_log(request)
    logger.info(datos_request)
    if request.method == "GET":
        if isadmin(current_user):
            logger.info("User id " + str(current_user.id) + " | " + current_user.username + " | ingresa a modificacion de usuario")
            userdata = db.get(Usuarios, id)
            if validacion_usuario_soporte(id, current_user.id):
                return render_template("mod_usuarios/modificaru.html", userdata=userdata)
            else:
                mensaje = f"El usuario:  {userdata.username}  no puede ser modificado"
                flash({"title": "Chronos SNI", "message": mensaje}, "error")
            return redirect(url_for("usuarios.send_usuarios"))
        else:

            return redirect(url_for("dashboard.dashboard_page"))
    else:

        userdata = db.get(Usuarios, id)
        userdata.username = request.form["username"]
        userdata.nombres = request.form["nombres"]
        userdata.apellidos = request.form["apellidos"]
        userdata.ci = request.form["ci"]
        if id == "2":
            rol = "admin"
        else:
            rol = request.form["rol"]
        userdata.rol = rol
        fecham = datetime.now()
        userdata.fecham = fecham.strftime("%Y/%m/%d %H:%M:%S")
        db.commit()
        logger.info("User id " + str(current_user.id) + " | " + current_user.username + " | modifica usuario: " + str(userdata.id))
        mensaje = f"Usuario: {current_user.username} modifico el usuario id {str(userdata.id)}"
        flash({"title": "Chronos SNI", "message": mensaje}, "success")
        return redirect(url_for("usuarios.send_usuarios"))


@usuarios.route("/borraru/<id>")
@login_required
def borraru(id):
    datos_request = datos_log(request)
    logger.info(datos_request)
    if isadmin(current_user):

        userdata = db.get(Usuarios, id)
        if id == "2":
            mensaje = f"El usuario:  {userdata.username}  no puede ser marcado como borrado"
            flash({"title": "Chronos SNI", "message": mensaje}, "warning")
            return redirect(url_for("usuarios.send_usuarios"))
        else:
            fecha = datetime.now()
            userdata.fecham = fecha.strftime("%Y/%m/%d %H:%M:%S")
            userdata.deleted = True
            db.commit()
            logger.info("User id " + str(current_user.id) + " | " + current_user.username + " | Marca id: " + id + ", como borrado")
            mensaje = f"El usuario:  {userdata.username} fue marcado como borrado"
            flash({"title": "Chronos SNI", "message": mensaje}, "success")

            return redirect(url_for("usuarios.send_usuarios"))
    else:

        return redirect(url_for("dashboard.dashboard_page"))


@usuarios.route("/restauraru/<id>")
@login_required
def restauraru(id):
    datos_request = datos_log(request)
    logger.info(datos_request)
    if isadmin(current_user):
        userdata = db.get(Usuarios, id)
        fecha = datetime.now()
        userdata.fecham = fecha.strftime("%Y/%m/%d %H:%M:%S")
        userdata.deleted = False
        db.commit()
        logger.info("User id " + str(current_user.id) + " | " + current_user.username + " | Restaura el id: " + id)
        mensaje = f"El usuario:  {userdata.username} fue restaurado"
        flash({"title": "Chronos SNI", "message": mensaje}, "success")

        return redirect(url_for("usuarios.send_usuarios"))
    else:

        return redirect(url_for("dashboard.dashboard_page"))


@usuarios.route("/eliminaru/<id>")
@login_required
def eliminaru(id):
    datos_request = datos_log(request)
    logger.info(datos_request)
    if isadmin(current_user):
        userdata = db.get(Usuarios, id)

        if id == "2":
            mensaje = f"El usuario:  {userdata.username}  no puede ser eliminado"
            flash({"title": "Chronos SNI", "message": mensaje}, "warning")
            return redirect(url_for("usuarios.send_usuarios"))

        db.delete(userdata)
        db.commit()
        logger.info("User id " + str(current_user.id) + " | " + current_user.username + " | elimina el id: " + id)
        mensaje = f"El usuario:  {userdata.username} fue eliminado"
        flash({"title": "Chronos SNI", "message": mensaje}, "success")

        return redirect(url_for("usuarios.send_usuarios"))
    else:

        return redirect(url_for("dashboard.dashboard_page"))

templates/mod_usuarios/modificaru.html
{% extends './base/base.html' %} {% block title %} Chronos SNI | Modificar datos de usuario {% endblock %} {% block body %} {% include('partials/navbar.html') %}

<div class="card mb-1 text-white bg-dark mt-1">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <h5>Modificar datos de usuario</h5>
      <div class="btn-group">
        <a href="{{ url_for('usuarios.send_usuarios') }}" class="btn btn-secondary btn-sm">Retorno</a>
      </div>
    </div>

    <form action="/modificar_user/{{userdata.id}}" method="post" class="mt-2" onsubmit="return validarClaves()">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

      <div class="row">
        <div class="col">
          <input
            type="text"
            class="form-control"
            placeholder="Nombres de usuario"
            aria-label="Nombre de usuario"
            name="username"
            id="username"
            minlength="4"
            maxlength="10"
            value="{{userdata.username}}"
            autocomplete="username"
            required
          />

          <div id="usuario-id" data-id="{{userdata.id}}"></div>
          <script type="text/javascript">
            $(document).ready(function () {
              $("#username").keypress(function (event) {
                var key = event.which || event.keyCode;
                if (
                  (key != 32 && key < 65) ||
                  (key > 90 && key < 97) ||
                  (key > 122 && key != 241 && key != 209 && key != 225 && key != 233 && key != 237 && key != 243 && key != 250 && key != 193 && key != 201 && key != 205 && key != 211 && key != 218)
                ) {
                  toastr.options.closeButton = true;
                  toastr.options.progressBar = true;
                  toastr.options.positionClass = "toast-top-center";
                  toastr.options.timeOut = 1500;
                  toastr.error("Solo se permiten letras en el campo usuario");
                  return false;
                }
              });
            });
            $("#username").on("blur", function () {
              let username = $(this).val();
              const id = document.getElementById("usuario-id").dataset.id;

              if (username.length >= 4) {
                $.get("/check-username-mod", { username, id }, function (data) {
                  if (data.exists) {
                    toastr.options.closeButton = true;
                    toastr.options.progressBar = true;
                    toastr.options.positionClass = "toast-top-center";
                    toastr.options.timeOut = 1500;
                    toastr.error(`El nombre de usuario: ${username} ya esta en uso`, "Por favor escribir otro");
                    $("#username").focus();
                  } else {
                    toastr.options.closeButton = true;
                    toastr.options.progressBar = true;
                    toastr.options.positionClass = "toast-top-center";
                    toastr.options.timeOut = 1500;
                    toastr.success(`Nombre de usuario: ${username} disponible para registrar`);
                  }
                });
              }
            });
          </script>
        </div>
        <div class="col">
          <input type="text" class="form-control" placeholder="Nombres" aria-label="Nombres" name="nombres" id="nombres" minlength="4" maxlength="20" value="{{userdata.nombres}}" required />
          <script type="text/javascript">
            $(document).ready(function () {
              $("#nombres").keypress(function (event) {
                var key = event.which || event.keyCode;
                if (
                  (key != 32 && key < 65) ||
                  (key > 90 && key < 97) ||
                  (key > 122 && key != 241 && key != 209 && key != 225 && key != 233 && key != 237 && key != 243 && key != 250 && key != 193 && key != 201 && key != 205 && key != 211 && key != 218)
                ) {
                  toastr.options.closeButton = true;
                  toastr.options.progressBar = true;
                  toastr.options.positionClass = "toast-top-center";
                  toastr.options.timeOut = 1500;
                  toastr.error("Solo se permiten letras en el campo nombres");
                  return false;
                }
              });
            });
          </script>
        </div>
        <div class="col">
          <input type="text" class="form-control" placeholder="Apellidos" aria-label="Apellidos" name="apellidos" id="apellidos" minlength="4" maxlength="20" value="{{userdata.apellidos}}" required />
          <script type="text/javascript">
            $(document).ready(function () {
              $("#apellidos").keypress(function (event) {
                var key = event.which || event.keyCode;
                if (
                  (key != 32 && key < 65) ||
                  (key > 90 && key < 97) ||
                  (key > 122 && key != 241 && key != 209 && key != 225 && key != 233 && key != 237 && key != 243 && key != 250 && key != 193 && key != 201 && key != 205 && key != 211 && key != 218)
                ) {
                  toastr.options.closeButton = true;
                  toastr.options.progressBar = true;
                  toastr.options.positionClass = "toast-top-center";
                  toastr.options.timeOut = 1500;
                  toastr.error("Solo se permiten letras en el campo apellidos");
                  return false;
                }
              });
            });
          </script>
        </div>
        <div class="col">
          <input type="text" class="form-control" placeholder="Cédula" aria-label="Cédula" name="ci" id="ci" minlength="7" maxlength="8" value="{{userdata.ci}}" required />
          <script type="text/javascript">
            $(document).ready(function () {
              $("#ci").keypress(function (event) {
                var key = event.which || event.keyCode;
                if (key < 48 || key > 57) {
                  toastr.options.closeButton = true;
                  toastr.options.progressBar = true;
                  toastr.options.positionClass = "toast-top-center";
                  toastr.options.timeOut = 1500;
                  toastr.error("Solo se permiten números en el campo cédula");

                  return false;
                }
              });
            });
          </script>
        </div>
      </div>
      <div class="row mt-2">
        <div class="col">
          <input type="password" class="form-control" placeholder="clave" aria-label="clave" name="calve" id="clave" minlength="6" maxlength="10" required />
        </div>
        <div class="col">
          <input type="password" class="form-control" placeholder="confirmar clave" aria-label="confirmar clave" name="confirmacion" id="confirmacion" minlength="6" maxlength="10" required />
        </div>
      </div>
      <div class="row mt-2">
        <div class="col" style="text-align: center">
          {% if userdata.rol == "admin" %}
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="rol" id="gridRadios1" value="user" />
            <label class="form-check-label" for="gridRadios1">Usuario</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="rol" id="gridRadios2" value="admin" checked />
            <label class="form-check-label" for="gridRadios2">Administrador</label>
          </div>
          {% else %}
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="rol" id="gridRadios1" value="user" checked />
            <label class="form-check-label" for="gridRadios1">Usuario</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="rol" id="gridRadios2" value="admin" />
            <label class="form-check-label" for="gridRadios2">Administrador</label>
          </div>
          {% endif %}
        </div>
      </div>
      <div class="d-flex justify-content-end">
        <div class="row">
          <div class="col">
            <div class="btn-group">
              <button type="submit" class="btn btn-primary btn-sm">Guardar</button>
              <a href="{{ url_for('usuarios.send_usuarios') }}" class="btn btn-secondary btn-sm">Retorno</a>
            </div>
          </div>
        </div>
      </div>
    </form>
    <script>
      function validarClaves() {
        const clave = document.getElementById("clave").value;
        const confirmacion = document.getElementById("confirmacion").value;
        if (clave != confirmacion) {
          toastr.options.closeButton = true;
          toastr.options.progressBar = true;
          toastr.options.positionClass = "toast-top-center";
          toastr.options.timeOut = 1500;
          toastr.error("Las claves no cienciden.");

          return false;
        }
        return true;
      }
    </script>
  </div>
</div>

{% endblock %}

templates/mod_usuarios/registrou.html
{% extends './base/base.html' %} {% block title %} Chronos SNI | Registro de usuario {% endblock %} {% block body %} {% include('partials/navbar.html') %}

<div class="card mb-1 text-white bg-dark mt-1">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <h5>Registro de usuario</h5>
      <div class="btn-group">
        <a href="/dashboard" class="btn btn-secondary btn-sm">Inicio</a>
        <a href="{{ url_for('usuarios.send_usuarios') }}" class="btn btn-secondary btn-sm">Retorno</a>
        <a href="{{ url_for('authentication.logout') }}" class="btn btn-secondary btn-sm">Salir</a>
      </div>
    </div>

    <form action="/registraru" method="post" class="mt-2" onsubmit="return validarClaves()">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

      <div class="row">
        <div class="col">
          <input type="text" class="form-control" placeholder="Nombres de usuario" aria-label="Nombre de usuario" name="username" id="username" minlength="4" maxlength="10" required />

          <script type="text/javascript">
            $(document).ready(function () {
              $("#username").keypress(function (event) {
                var key = event.which || event.keyCode;
                if (
                  (key != 32 && key < 65) ||
                  (key > 90 && key < 97) ||
                  (key > 122 && key != 241 && key != 209 && key != 225 && key != 233 && key != 237 && key != 243 && key != 250 && key != 193 && key != 201 && key != 205 && key != 211 && key != 218)
                ) {
                  toastr.options.closeButton = true;
                  toastr.options.progressBar = true;
                  toastr.options.positionClass = "toast-top-center";
                  toastr.options.timeOut = 1500;
                  toastr.error("Solo se permiten letras en el campo usuario");
                  return false;
                }
              });
            });
            $("#username").on("blur", function() {
              let username = $(this).val();
              if (username.length >= 4) {
                $.get("/check-username", {username}, function(data) {
                  if (data.exists) {
                    toastr.options.closeButton = true;
                    toastr.options.progressBar = true;
                    toastr.options.positionClass = "toast-top-center";
                    toastr.options.timeOut = 1500;
                    toastr.error(`El nombre de usuario: ${username} ya esta en uso`, "Por favor escribir otro");
                    $("#username").val("").focus();
                  } else {
                    toastr.options.closeButton = true;
                    toastr.options.progressBar = true;
                    toastr.options.positionClass = "toast-top-center";
                    toastr.options.timeOut = 1500;
                    toastr.success(`Nombre de usuario: ${username} disponible para registrar`);
                  }
                })
              }
            });
          </script>
        </div>
        <div class="col">
          <input type="text" class="form-control" placeholder="Nombres" aria-label="Nombres" name="nombres" id="nombres" minlength="4" maxlength="20" required />
          <script type="text/javascript">
            $(document).ready(function () {
              $("#nombres").keypress(function (event) {
                var key = event.which || event.keyCode;
                if (
                  (key != 32 && key < 65) ||
                  (key > 90 && key < 97) ||
                  (key > 122 && key != 241 && key != 209 && key != 225 && key != 233 && key != 237 && key != 243 && key != 250 && key != 193 && key != 201 && key != 205 && key != 211 && key != 218)
                ) {
                  toastr.options.closeButton = true;
                  toastr.options.progressBar = true;
                  toastr.options.positionClass = "toast-top-center";
                  toastr.options.timeOut = 1500;
                  toastr.error("Solo se permiten letras en el campo nombres");
                  return false;
                }
              });
            });
          </script>
        </div>
        <div class="col">
          <input type="text" class="form-control" placeholder="Apellidos" aria-label="Apellidos" name="apellidos" id="apellidos" minlength="4" maxlength="20" required />
          <script type="text/javascript">
            $(document).ready(function () {
              $("#apellidos").keypress(function (event) {
                var key = event.which || event.keyCode;
                if (
                  (key != 32 && key < 65) ||
                  (key > 90 && key < 97) ||
                  (key > 122 && key != 241 && key != 209 && key != 225 && key != 233 && key != 237 && key != 243 && key != 250 && key != 193 && key != 201 && key != 205 && key != 211 && key != 218)
                ) {
                  toastr.options.closeButton = true;
                  toastr.options.progressBar = true;
                  toastr.options.positionClass = "toast-top-center";
                  toastr.options.timeOut = 1500;
                  toastr.error("Solo se permiten letras en el campo apellidos");
                  return false;
                }
              });
            });
          </script>
        </div>
        <div class="col">
          <input type="text" class="form-control" placeholder="Cédula" aria-label="Cédula" name="ci" id="ci" minlength="7" maxlength="8" required />
          <script type="text/javascript">
            $(document).ready(function () {
              $("#ci").keypress(function (event) {
                var key = event.which || event.keyCode;
                if (key < 48 || key > 57) {
                  toastr.options.closeButton = true;
                  toastr.options.progressBar = true;
                  toastr.options.positionClass = "toast-top-center";
                  toastr.options.timeOut = 1500;
                  toastr.error("Solo se permiten números en el campo cédula");

                  return false;
                }
              });
            });
          </script>
        </div>
      </div>
      <div class="row mt-2">
        <div class="col">
          <input type="password" class="form-control" placeholder="clave" aria-label="clave" name="clave" id="clave" minlength="6" maxlength="10" required />
        </div>
        <div class="col">
          <input type="password" class="form-control" placeholder="confirmar clave" aria-label="confirmar clave" name="confirmacion" id="confirmacion" minlength="6" maxlength="10" required />
        </div>
      </div>
      <div class="container mt-2">
        <div class="row">
          <div class="col" style="text-align: center">
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="rol" id="gridRadios1" value="user" checked />
              <label class="form-check-label" for="gridRadios1">Usuario</label>
            </div>
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="rol" id="gridRadios2" value="admin" />
              <label class="form-check-label" for="gridRadios2">Administrador</label>
            </div>
          </div>
        </div>
      </div>

      <div class="d-flex justify-content-end">
        <div class="row">
          <div class="col">
            <div class="btn-group">
              <button type="submit" class="btn btn-primary btn-sm">Registrar</button>
              <a href="{{ url_for('usuarios.send_usuarios') }}" class="btn btn-secondary btn-sm">Retorno</a>
              <a class="btn btn-secondary btn-sm" href="{{ url_for('authentication.logout') }}">Salir</a>
            </div>
          </div>
        </div>
      </div>
    </form>
    <script>
      function validarClaves() {
        const clave = document.getElementById("clave").value;
        const confirmacion = document.getElementById("confirmacion").value;
        if (clave != confirmacion) {
          toastr.options.closeButton = true;
          toastr.options.progressBar = true;
          toastr.options.positionClass = "toast-top-center";
          toastr.options.timeOut = 1500;
          toastr.error("Las claves no cienciden.");

          return false;
        }
        return true;
      }
    </script>
  </div>
</div>

{% endblock %}